---
title: "p8105 hw5 solutions"
author: "Shuhong Xiang"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document

---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

Load the data.

```{r}
homcide_df =
  read_csv("homcide_data/homicide-data.csv") %>%
  mutate(
    city_state = str_c(city, state, sep = "_"), 
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved",
    )
  ) %>%
  select(city_state, resolved) %>%
  filter(city_state != "Tulsa_AL")

```

```{r}
aggregate_df = 
  homcide_df %>%
  group_by(city_state) %>%
  summarise(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )
```

Prop test for a dingle city: 

```{r}
prop.test(
  aggregate_df%>%filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved), 
  aggregate_df%>%filter(city_state == "Baltimore_MD") %>% pull(hom_total)) %>%
  broom::tidy()
```

Try to iterate:

```{r}
results_df = 
  aggregate_df %>%
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>%
  select(-prop_tests) %>%
  unnest(tidy_tests) %>%
  select(city_state, estimate, conf.low, conf.high)
```

```{r}
results_df %>%
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate))+
  geom_point() + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

## Problem 2

Create path_df containing all data from the csv:

```{r}
path_df =
  tibble(
  path = list.files("lda_data"),
) %>%
  mutate(path = str_c("lda_data/", path),
         data = map(path, read_csv)
           )%>%
  unnest(data)

path_df
```

Clean the datafram:

```{r}
tidy_lda =
  path_df %>%
  mutate(
    path = str_remove_all(path,"lda_data/"), 
    path = str_remove_all(path,".csv")
  ) %>%
  separate(path, into = c("group","subject_id"), sep = 3) %>%
  mutate(
    subject_id = str_remove_all(subject_id, "_"),
    group = str_replace(group,"con","control"),
    group = str_replace(group,"exp","experiment")
  )%>%
  pivot_longer(
    week_1:week_8,
    names_prefix = "week_",
    names_to = "week",
    values_to = "weekly observations"
  )%>%
  mutate(week = as.numeric(week))
tidy_lda
```


## Problem 3

